### ISSUE TITLE
Single quote in Dataset or Institution name breaks queries

### ISSUE THREAD

**Issue by villanueval** [Smithsonian/GBIF-Issues-Explorer#6]
Insert queries fail when a dataset or institution name has a single quote, like:

> The mammals collection (ZM) of the Muséum national d'Histoire naturelle (MNHN - Paris)
> Dataset [3959ee49-7678-4a88-9049-5dfc55ccebf3](https://www.gbif.org/dataset/3959ee49-7678-4a88-9049-5dfc55ccebf3)

**Comment by ljvillanueva** [comment]
Fixed in https://github.com/Smithsonian/GBIF-Issues-Explorer/commit/4b66d71a4fb14f1499d95dc2dea6b2843f02c9c0
